name: example-ec2-tools-step-plugin
version: 1.0
rundeckPluginVersion: 1.0
author: Alex Honor
date: 07/20/14
providers:
  - name: ec2-tools-step-plugin
    service: WorkflowNodeStep
    title: Run ec2-tools command.
    description: Calls a command from the Amazon EC2 API Tools.
    plugin-type: script
    script-interpreter: /bin/bash
    script-file: nodestep.sh
    script-args: '${node.name} ${config.command} ${config.arguments}'
    config:
      - type: String
        name: command
        title: Command
        description: The ec2 tool command
      - type: String
        name: arguments
        title: Arguments
        description: The command arguments
        default: ''
      - type: Boolean
        name: verbose
        title: Verbose
        description: Display verbose output.
        default: false
      - type: Select
        name: region
        title: Region
        description: The region
        default: us-east-1
        values:
          - us-east-1
          - us-west-2
          - us-west-1
          - eu-west-1
          - ap-southeast-1
          - ap-southeast-2
          - ap-northeast-1
          - sa-east-1
      - type: String
        name: EC2_BASE
        title: The base directory for ec2-tools
        description: The base directory for ec2-tools
        scope: Project
      - type: String
        name: EC2_URL
        title: The EC2_URL
        description: The EC2_URL
        default: https://ec2.amazonaws.com
        scope: Project     
      - type: String
        name: AWS_ACCESS_KEY
        title: The AWS_ACCESS_KEY
        description: The AWS_ACCESS_KEY
        scope: Project        
      - type: String
        name: AWS_SECRET_KEY
        title: The AWS_SECRET_KEY
        description: The AWS_SECRET_KEY
        scope: Project        
      - type: String
        name: JAVA_HOME
        title: The JAVA_HOME
        description: The JAVA_HOME
        scope: Project   
